backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
locale: 'es'
collections:
  - name: 'publicaciones'
    label: 'Publicaciones'
    folder: 'content/publicaciones'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string' , required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
      - { label: 'Archivo Adjunto', name: 'file', widget: 'file', required: false }
  - name: 'reportajes'
    label: 'Reportajes Periodísticos'
    folder: 'content/reportajes'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
      - { label: 'Archivo Adjunto', name: 'file', widget: 'file', required: false }
  - name: 'columnas'
    label: 'Columnas de Opinión'
    folder: 'content/columnas'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Enlace artículo', name: 'link', widget: 'string', required: false }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion","think-tanks"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'noticias'
    label: 'Noticias'
    folder: 'content/noticias'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Enlace artículo', name: 'link', widget: 'string', required: false }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion","think-tanks"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'eventos'
    label: 'Eventos'
    folder: 'content/columnas'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Enlace artículo', name: 'link', widget: 'string', required: false }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion","think-tanks"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'videos'
    label: 'Videos'
    folder: 'content/videos'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Enlace video', name: 'video', widget: 'string' }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown', required: false }


