backend:
  name: git-gateway
  branch: mainsite # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
locale: 'es'
slug:
      encoding: "ascii"
      clean_accents: true
      sanitize_replacement: "_"
collections:
  - name: 'publicaciones'
    label: 'Publicaciones'
    label_singular: 'publicación'
    folder: 'content/publicaciones'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string' , required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
      - { label: 'Archivo Adjunto', name: 'file', widget: 'file', required: false }
  - name: 'reportajes'
    label: 'Reportajes Periodísticos'
    folder: 'content/reportajes'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
      - { label: 'Archivo Adjunto', name: 'file', widget: 'file', required: false }
  - name: 'columnas'
    label: 'Columnas de Opinión'
    folder: 'content/columnas'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Medio', name: 'medio', widget: 'string' }
      - { label: 'Enlace artículo', name: 'link', widget: 'string', required: false }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion","think-tanks"]}
      - { label: 'Extracto', name: 'extracto', widget: 'string', required: false }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'noticias'
    label: 'Noticias'
    folder: 'content/noticias'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Enlace artículo', name: 'link', widget: 'string', required: false }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion","think-tanks"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'eventos'
    label: 'Eventos'
    folder: 'content/eventos'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Enlace artículo', name: 'link', widget: 'string', required: false }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion","think-tanks"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'videos'
    label: 'Videos'
    folder: 'content/videos'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Enlace video', name: 'video', widget: 'string' }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["anticorrupcion", "finanzas-publicas", "desarrollo-sostenible","ciudades-del-futuro","inclusion"]}
      - { label: 'Contenido', name: 'body', widget: 'markdown', required: false }
  - name: 'financiadores'
    label: 'Financiadores'
    folder: 'content/financiadores'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Financiador', name: 'nombre', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Url', name: 'link', widget: 'string', required: false }
  - name: 'personal'
    label: 'Equipo'
    folder: 'content/personal'
    format: 'frontmatter'
    create: true
    slug: '{{nombre}}'
    editor:
      preview: false
    fields:
      - { label: 'Nombre', name: 'nombre', widget: 'string' }
      - { label: 'Foto', name: 'foto', widget: 'image', required: false }
      - { label: 'Puesto', name: 'puesto', widget: 'string' }
      - { label: 'Semblanza', name: 'semblanza', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string', required: false }
      - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
  - name: 'trabajos'
    label: 'Bolsa de Trabajo'
    label_singular: 'Vacante'
    folder: 'content/bolsatrabajo'
    format: 'frontmatter'
    create: true
    slug: '{{puesto}}'
    editor:
      preview: false
    fields:
      - { label: 'Puesto', name: 'puesto', widget: 'string' }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["vacantes","internships"]}
      - { label: 'Descripción', name: 'body', widget: 'markdown' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Área', name: 'area', widget: 'string', required: false }
  - name: 'documentos'
    label: 'Docs Institucionales'
    label_singular: 'Documento'
    folder: 'content/documentos'
    format: 'frontmatter'
    create: true
    slug: '{{titulo}}'
    editor:
      preview: false
    fields:
      - { label: 'Titulo', name: 'titulo', widget: 'string' }
      - { label: 'Fecha Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen Principal', name: 'img', widget: 'image', required: false }
      - { label: 'Imagen Alt', name: 'img-alt', widget: 'string', required: false }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'Archivo Adjunto', name: 'file', widget: 'file', required: false }

